# Generated by Django 4.2.1 on 2023-05-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='location_name',
            new_name='memory_name',
        ),
    ]
